### PR TITLE
Fix setup installation script

### PR DESCRIPTION
**Pull request by mattpitkin**
Fix the installation issues seen in #7. The main things (I think) have been to use the `setuptools` `find_packages` function and remove the `ext_packages` variables from the setup function, but there may be other fixes. This also fixes some typos in `setup.py` and removes `general.c` from the stats directory, as it will generally be different for people.

An alternative would be to switch `setup.py` to use `setuptools` entirely, e.g.:
```
from setuptools import setup, find_packages
from setuptools import Extension

import os, sys, numpy

ext_modules = [ Extension("bayesflare.stats.general", 
                          sources =[ "bayesflare/stats/log_marg_amp_full.c", "bayesflare/stats/general.pyx"], 
                          include_dirs=[numpy.get_include(), '.', os.popen('gsl-config --cflags').read()[2:-1]],  
                          library_dirs=['.', os.popen('gsl-config --libs').read().split()[0][2:]], 
                          libraries=['gsl', 'gslcblas'], extra_compile_args=['-O3']) ]

#directives = {'embedsignatjobsure': True} # embed cython function signature in docstring

setup(
  name = 'bayesflare',
  version = '1.0.2',
  url = 'https://github.com/BayesFlare/bayesflare',
  description = 'Python functions and classes implementing a Bayesian approach to flare finding.',
  author = 'Matthew Pitkin, Daniel Williams',
  author_email = 'matthew.pitkin@gla.ac.uk',
  packages = find_packages(),
  setup_requires = ['numpy'],
  install_requires = ['numpy', 'scipy', 'cython'],
  ext_modules = ext_modules,
  classifiers=[
      'Development Status :: 5 - Production/Stable',
      'Intended Audience :: Science/Research',
      'License :: OSI Approved :: GNU General Public License (GPL)',
      'Operating System :: POSIX :: Linux',
      'Programming Language :: Python',
      'Programming Language :: C',
      'Natural Language :: English',
      'Topic :: Scientific/Engineering :: Astronomy',
      'Topic :: Scientific/Engineering :: Information Analysis'
      ]
)
```
but there are some things (like the cython compiler directives) that I don't know how to include in this.

@transientlunatic - could you take a quick look at this and see if it looks ok?

### CODE REVIEW

**Comment by mattpitkin** [comment]
I should add that this now just installs bayesflare as an egg.

**Comment by transientlunatic** [comment]
I'll try installing this in a virtual environment on my machine today and check everything looks like it works for me too.

**Comment by transientlunatic** [comment]
Hmm, I've identified another problem with the setup script; if Cython isn't already installed on the system you'll get an import error:
`ImportError: No module named Cython.Distutils`
which gets thrown even if Cython is listed as a build requirement (since the setup never reaches that point).

**Comment by mattpitkin** [comment]
I suppose we could just add:
```
try:
  from Cython.Distutils import build_ext
￼  from Cython.Build import cythonize
except ImportError:
  raise ImportError('Cython not installed on system')
```
Would that be ok?

**Comment by transientlunatic** [comment]
I'm looking to see if there's a way we can get the setup script to still install Cython; I feel like there must be a better way to do this...

**Comment by transientlunatic** [comment]
One approach is probably to include the C source which cython generates (see http://stackoverflow.com/questions/4505747/how-should-i-structure-a-python-package-that-contains-cython-code).

**Comment by transientlunatic** [comment]
Likewise, we'll need to bootstrap the installation of Numpy to build the extension (see http://stackoverflow.com/questions/19919905/how-to-bootstrap-numpy-installation-in-setup-py)

**Comment by mattpitkin** [comment]
> One approach is probably to include the C source which cython generates (see http://stackoverflow.com/questions/4505747/how-should-i-structure-a-python-package-that-contains-cython-code).

An issue with this seems to be that the C source that cython generates contains library paths that are specific to the use that generated it, so it's not guaranteed to work for everyone...

... although looking again at the generated C file, it looks like these paths are only in comment blocks rather than the actual code, so it's probably ok.

**Comment by transientlunatic** [comment]
Hmm, so even with the change to setuptools, and bootstrapping numpy so that the include directories are added to the correct search path I still get the original error when I try to install in a clean virtualenv.

**Comment by mattpitkin** [comment]
I'm wondering if adding the following to `setup`
```
package_data = {'': ['*.c']}
```
or
```
package_data = {'': ['stats/*.c']}
```
might work?

**Comment by mattpitkin** [comment]
I've made some further changes to `setup.py` that should hopefully fix things. With this I have built locally, where I have Cython, with
```
python setup.py install
```
to produce the `general.c` file from `general.pyx`. I then create a source package with:
```
python setup.py sdist
```
I've copied the tarball created by this to a machine without cython, and been able to build successfully again with:
```
python setup.py install --user
```

If you can also get this to work I'll run
```
python setup.py sdist upload
```
to add the updates to pypi.

**Comment by mattpitkin** [comment]
As additional info - the updates to `setup.py` include the `.c/h` files in the source distribution that is created.

**Comment by transientlunatic** [comment]
Sorry for taking so long to look at this!
I think I'd made a similar change to the code, but forgot to push it a while back. I've merged my and your work together. I think I made the changes to get around source installation when numpy isn't installed too.

I've built and installed this on a clean system, and all of the dependencies and the C module seem to build correctly. 

@mattpitkin if you're happy with the changes I've made in the merge resolution I'm happy to merge this into master. I'll then push the sdist and the wheel to pypi.

:+1:

**Comment by mattpitkin** [comment]
In addition to removing out some of the commented out lines, I've made another minor change. If Cython exists then it imports `cythonize`, so that we can pass the `directives` argument to it (I seem to recall this is required for the documentation from the `.pyx` file to be included?)

**Comment by mattpitkin** [comment]
@transientlunatic I'm happy for you to merge this, if you're happy with my other minor change?

**Comment by transientlunatic** [comment]
Yep, that all looks good to me. I'll do the merge and then push the distribution up to pypi.

**Comment by mattpitkin** [comment]
Great, are you back in the UK, or just up really early?

**Comment by transientlunatic** [comment]
Just up early; I fly back today.

**Comment by mattpitkin** [comment]
Cool. Well have a safe trip back and I'll see you soon.

**Pull request merged**
